# Generated by Django 3.2.5 on 2021-07-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210708_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='id',
            new_name='uuid',
        ),
    ]
