# Generated by Django 3.2.5 on 2021-07-12 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20210712_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='id',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
