# Generated by Django 3.2.5 on 2021-07-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20210712_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='uuid',
            new_name='id',
        ),
    ]
